# Codeceptjs based BDD testing

name: $(Build.DefinitionName).$(BuildID).$(Rev:.rr)

trigger:
- main

pool:
  name: 'Hosted VS2017'
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

#- script: |
#   npm run sim-dev3 &
#  displayName: 'sim dev3'

- script: |
    $env:CI=true 
    npm run test-junit -- --grep "(?=.*@saml)(?=.*@logout)"
    dir C:\npm\cache\_logs
  displayName: 'Run tests'

- script: |
    cat /home/vsts/.npm/_logs/*
  displayName: display all logs

- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: output/test-results.xml

- script: |
   ls output
