# Codeceptjs based BDD testing

name: $(Build.DefinitionName).$(BuildID).$(Rev:.rr)

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

#- script: |
#   npm run sim-dev3 &
#  displayName: 'sim dev3'

- script: |
    CI=true, CSP_HOST=TST1 npm run test-junit -- --grep "(?=.*@saml)(?=.*@mustapha)"
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: output/test-results.xml

- script: |
   ls output
